language: python
python:
    - "2.6"
    - "2.7"
install: 
    - "pip install -r requirements.txt"
    - "pip install coverage"
    - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
    - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then pip install coveralls; fi
    - if [[ $TRAVIS_PYTHON_VERSION != 2* ]]; then pip install sphinx; fi
script:
    - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then flake8 .; fi
    - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then
        coverage run --source=coshsh setup.py test;
      else
        python setup.py test;
      fi
    - if [[ $TRAVIS_PYTHON_VERSION != 2* ]]; then
        python setup.py build_sphinx;
      fi
after_success:
    coveralls
